# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml" #mandatory

# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
# See "https://maven.apache.org/enforcer/enforcer-rules/versionRanges.html"
# 24 is 1.13-pre, 25 is 1.13.2, 26 is 1.14.2, 27 is 1.14.3, 28 is 1.14.4, 29 is 1.15, 30 is 1.15.1, 31 is 1.15.2
loaderVersion="[31,)" #mandatory

# A URL to refer people to when problems occur with this mod
issueTrackerURL="http://github.com/YourName/Your-Mod-Name/issues" #optional

# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory
# The modid of the mod
modId="easyenchantments" #mandatory
# The version number of the mod - there's a few well known ${} variables useable here or just hardcode it
version="${version}" #mandatory
# A display name for the mod
displayName="Easy Enchantments" #mandatory
# A URL to query for updates for this mod. See the JSON update specification <here>
updateJSONURL="http://github.com/YourName/Your-Mod-Name/update.json" #optional
# A URL for the "homepage" for this mod, displayed in the mod UI
displayURL="http://github.com/YourName/Your-Mod-Name" #optional
# A file name (in the root of the mod JAR) containing a logo for display
logoFile="easystorage.png" #optional
# A text field displayed in the mod UI
credits="Beerik" #optional
# A text field displayed in the mod UI
authors="Beerik" #optional
# The description text for the mod (multi line!) (#mandatory)
description='''
An easy way to enchant and disenchant your items
'''